vector_store:
  provider: "chromadb"
  persist_directory: "./data/vector_store"
  collections:
    - name: "document_chunks"
      embedding_function: "google"
    - name: "atomic_facts" 
      embedding_function: "google"
    - name: "temporal_events"
      embedding_function: "google"
    - name: "domain_entities"
      embedding_function: "google"

embedding:
  primary_provider: "google"
  fallback_provider: "openai"
  local_provider: "sentence_transformers"
  batch_size: 32
  max_tokens: 512
  
  providers:
    google:
      model: "text-embedding-004"
      api_key_env: "GOOGLE_API_KEY"
    openai:
      model: "text-embedding-3-small"
      api_key_env: "OPENAI_API_KEY"
    sentence_transformers:
      model: "all-MiniLM-L6-v2"
      device: "cpu"

search:
  similarity_threshold: 0.7
  max_results: 50
  hybrid_weights:
    vector: 0.6
    graph: 0.3
    lexical: 0.1
  
  ranking:
    temporal_weight: 0.2
    confidence_weight: 0.3
    diversity_factor: 0.1

temporal:
  enable_temporal_search: true
  temporal_decay_factor: 0.95
  max_temporal_range_days: 365
  temporal_resolution: "day"

graph:
  backend: "networkx"
  max_depth: 3
  relationship_weights: true
  
knowledge_domains:
  - name: "general"
    confidence_threshold: 0.8
  - name: "technical"
    confidence_threshold: 0.9
  - name: "business"
    confidence_threshold: 0.85

api:
  host: "localhost"
  port: 8000
  workers: 1
  reload: true

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./logs/app.log"

performance:
  vector_cache_size: 1000
  query_timeout_seconds: 30
  max_concurrent_queries: 50
  enable_metrics: true